[bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"pyproject.toml" = [
    '^version = "{version}"$',
]
"STanalysis/__init__.py" = [
    '^__version__ = "{version}"$',
]
